export const projects = [
  {
    title: "World Atlas",
    stack: "React.js · JavaScript · CSS",
    category: "Interactive web app",
    year: "2024",
    desc: "An interactive atlas for exploring countries with real-time filtering and a polished, responsive layout.",
    impact: "Makes regional discovery feel effortless for students, travelers, and curious users.",
    highlights: ["Live search and country filtering", "Responsive UI for all screen sizes", "Clean data presentation with quick navigation"],
    github: "https://github.com/vinayaka2003/World-Atlas",
    demo: "https://project1-indol-xi.vercel.app",
    accent: "from-sky-500 via-cyan-500 to-blue-600",
    featured: true,
  },
  {
    title: "Weather Application",
    stack: "React.js · JavaScript · CSS · Vite",
    category: "Utility app",
    year: "2024",
    desc: "A responsive weather experience that brings forecasts, conditions, and location-based insights into one streamlined view.",
    impact: "Helps users check weather details quickly without friction or clutter.",
    highlights: ["Instant city search", "Live weather metrics and conditions", "Mobile-friendly experience"],
    github: "https://github.com/vinayaka2003/Weather-App.git",
    demo: "https://weather-application1-smoky.vercel.app",
    accent: "from-emerald-500 via-teal-500 to-cyan-600",
    featured: false,
  },
  {
    title: "UIDAI Data Analysis System",
    stack: "Python · Pandas · NumPy",
    category: "Data analysis",
    year: "2023",
    desc: "Processed 300K+ records to uncover patterns, automate data cleaning, and surface actionable insights.",
    impact: "Turned a large raw dataset into a more useful decision-making asset.",
    highlights: ["Large-scale data cleaning", "Statistical analysis and pattern discovery", "Insight-focused reporting"],
    github: "https://github.com/vinayaka2003/uidai_project",
    accent: "from-violet-500 via-fuchsia-500 to-pink-600",
    featured: false,
  },
  {
    title: "AI Order System",
    stack: "React · Flask · SQLite",
    category: "AI workflow",
    year: "2024",
    desc: "An AI-powered order workflow that lets users manage requests through a conversational interface and a lightweight backend.",
    impact: "Brings a more natural interaction model to everyday order management tasks.",
    highlights: ["Natural-language order creation", "FastAPI-backed workflow", "Simple, practical state management"],
    github: "https://github.com/vinayaka2003/AI-Order-System",
    demo: "https://ai-order-system-1.onrender.com",
    accent: "from-amber-500 via-orange-500 to-rose-600",
    featured: false,
  },
  {
    title: "Goldstone Fitness Website",
    stack: "Next.js · React · JavaScript · CSS Modules · Vercel",
    category: "Business website",
    year: "2026",
    desc: "A premium gym website designed to help fitness centres establish a strong online presence, showcase memberships, trainers, facilities, and generate enquiries through WhatsApp.",
    impact: "Provides local gyms with a modern digital presence that helps attract new members and build trust.",
    highlights: [
      "Premium responsive design",
      "WhatsApp enquiry integration",
      "Membership plans, trainers & gallery",
      "SEO-friendly and high performance",
      "Optimized for desktop and mobile"
    ],
    github: "https://github.com/vinayaka2003/gym-website",
    demo: "https://goldstone-fitness.vercel.app",
    accent: "from-red-500 via-orange-500 to-yellow-500",
    featured: true,
  },
  {
    title: "Digital Product Store",
    stack: "Next.js · React · JavaScript · CSS Modules · Razorpay",
    category: "E-commerce",
    year: "2026",
    desc: "A modern digital storefront for selling ebooks, templates, courses, and downloadable assets with secure online payments.",
    impact: "Enables creators and businesses to sell digital products through a fast, professional, and mobile-friendly platform.",
    highlights: [
      "Razorpay payment integration",
      "Instant digital product delivery",
      "Responsive product pages",
      "Optimized checkout experience",
      "Scalable architecture"
    ],
    github: "https://github.com/vinayaka2003/digital-store",
    demo: "https://your-digital-store.vercel.app",
    accent: "from-indigo-500 via-violet-500 to-fuchsia-600",
    featured: true,
  },
  {
    title: "Habee Craft",
    stack: "Next.js · FastAPI · PostgreSQL · SQLAlchemy · JWT",
    category: "Full-Stack E-commerce",
    year: "2026",
    desc: "A modern e-commerce platform built for handmade gifts, bouquets, and custom crafts. It includes secure authentication, product browsing, shopping experience, and an admin-ready architecture.",
    impact: "Helps small businesses showcase and sell handmade products through a fast, scalable, and professional online store.",
    highlights: [
      "Full-stack architecture with Next.js & FastAPI",
      "JWT authentication and user accounts",
      "Product catalog with categories",
      "Responsive shopping experience",
      "PostgreSQL database with SQLAlchemy"
    ],
    github: "https://github.com/vinayaka2003/habee-craft",
    demo: "https://habeecraft.vercel.app",
    accent: "from-pink-500 via-rose-500 to-orange-500",
    featured: true,
  },
];
